syntax = "proto3";
package proto.message;

// A log entry to be persisted.
//
// `data` is an opaque bag of application-specific bytes which are only copied
// around, but never modified by the raft protocol.
message Entry {
  uint64 term = 1;
  uint64 index = 2;
  bytes data = 3;
}

message ProtoMessage {
  ProtoMessageType msg_type = 1;
  uint64 to = 2;
  uint64 from = 3;
  uint64 term = 4;
  uint64 commit = 5;
  uint64 last_term = 6;
  uint64 last_index = 7;
  repeated Entry entries = 8;
  uint64 voted_for = 9;
  bool success = 10;
}

enum ProtoMessageType {
  Heartbeat = 0;
  HeartbeatResponse = 1;
  AppendEntries = 2;
  AppendEntriesResponse = 3;
  RequestVote = 4;
  RequestVoteResponse = 5;
}
