[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
driver = { path = "../driver" }
raft = { path = "../raft" }
proto = { path = "../proto" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.10.1"
smol = "2"
async-channel = "2"
async-h1 = "2"
http-types = "2"
async-net = "2"
async-lock = "3"
futures-lite = "2"
